### ISSUE TITLE
Cannot run the command npm run server, just loads indefinately

### ISSUE THREAD

**Issue by TheOdiumWitch** [dunstad/roboserver#10]
I cloned the repository and managed to get past npm install, yet when I run npm run server it begins but stops at >node .bin/www
Can you provide any insight as to why this is?

**Comment by dunstad** [comment]
I've got some free time so I'll try!

Are you using the master branch or one of the releases?

**Comment by TheOdiumWitch** [comment]
release 1.0.1

**Comment by TheOdiumWitch** [comment]
It might just be easier to post the desktop version though, as I have been working on this all day.

**Comment by dunstad** [comment]
The desktop version is under assets on the 1.0.1 release.

**Comment by TheOdiumWitch** [comment]
"The code execution cannot proceed because ffmpeg.dll was not found. Reinstalling the program may fix this problem."
I tried reinstalling it twice.

**Comment by dunstad** [comment]
I have good news for you. The output you saw when you first posted this issue is what you should see when it works. After it stops there, go to localhost:8080 in your browser and you should be able to see it. The second error you posted occurred because the server was already running once, so the second one couldn't use the port it wanted to.

I should put in some message in the terminal telling people to do that, so I'll leave this open until I do as a reminder.

**Comment by dunstad** [comment]
I'll take the .exe down for now since it doesn't appear to work for me either.

**Comment by TheOdiumWitch** [comment]
It would seem that 
>npm run server 
cannot find the module 'express'

**Comment by TheOdiumWitch** [comment]
any tips?

**Comment by dunstad** [comment]
I'm afraid I can't reproduce that on my end. Everything worked properly just like it did your first time.

**Comment by TheOdiumWitch** [comment]
I could send the full error if you think that might help?

**Comment by dunstad** [comment]
I've got no idea what changes you might have made on your end, but given that you managed to get it working once before, I'd recommend starting from the beginning again as the way most likely to work. I can understand your reluctance given the time you've put in, however.

**Comment by TheOdiumWitch** [comment]
Ok, thank you

**Comment by dunstad** [comment]
Added a new release (1.0.2) with a desktop version that hopefully works and a message from the server that lets you know it worked and where to go to see it.
