### ISSUE TITLE
Not working for latest version of OpenComputers?

### ISSUE THREAD

**Issue by dunstad** [dunstad/roboserver#12]

**Comment by dunstad** [comment]
I was able to run the code after manually downloading commandMap.lua . I fixed the setup script to download that file automatically in (this commit)[https://github.com/dunstad/roboserver/commit/938df00b9cf126bd45af8e34779b98bb3400540d], so everything should work as described in the documentation now for Minecraft 1.12.2, OpenComputers 1.7.4 (the current newest version).

**Comment by isaaachipkiss** [comment]
How the fuck do I find the Roboserver Ip and port? You never even explained what those were!!

**Comment by dunstad** [comment]
You can piss off with that attitude. Good luck figuring it out.

**Comment by isaaachipkiss** [comment]
It was a bad day.
