### ISSUE TITLE
Add a way of clearing scan data without closing the program

### ISSUE THREAD

**Issue by agent55511** [dunstad/roboserver#13]
I tested this out with Opencomputers 1.7.4 on MC 1.12.2. There were a few moments when the robots location de-synced with the roboserver causing block placements to fail, but aside from that it works very well. The only issue is that with large amounts of scan data, the program slows down rendering it. There should be some way to clear all scan data without having to close the program.

**Comment by dunstad** [comment]
When using the browser a refresh does the trick. I'll make it so that works on the desktop version too.

Eventually I would like to make the rendering more performant so this isn't necessary.

**Comment by dunstad** [comment]
1.0.3 has refreshing with Ctrl + R or F5 in the desktop version, so I'm going to close this. If you have any more trouble let me know!
