### ISSUE TITLE
How???

### ISSUE THREAD

**Issue by isaaachipkiss** [dunstad/roboserver#17]
You never explained Roboserver's Ip and port, and I still have no damn idea how to find them, and I'm using the standalone version!

**Comment by dunstad** [comment]
Closed for being a jerk.

**Comment by isaaachipkiss** [comment]
I still have no Idea how, my anger isn't without reason. You seemingly skipped a step in your instructions. However, I apologize as it was a bad night for me and I was already in a bad mood.

To be clear, I seemingly need network info for the setup, but the desktop version doesn't declare this info anywhere. I looked around the info on github with no success.

Again, sorry for being a dick.
