### ISSUE TITLE
Nothing shows up in the browser...

### ISSUE THREAD

**Issue by polyzium** [dunstad/roboserver#2]
MC 1.10.2, OC 1.6.2.7
Using Iridium (Chromium fork), version 58.0. Also tried Firefox 54.0.1, still nothing.

Steps to reproduce the problem:
- Install RoboServer web server
- Install RoboServer client on the robot
- Link them together
- Fiddle around with options
- See the results
- Get frustrated when nothing shows up (lol kek)

The expected behavior:
After selecting the robot and setting Scan Size not to None, a map should appear.

The actual behavior:
Nothing shows up.

![image](https://user-images.githubusercontent.com/22579935/28340887-03107ed6-6c1a-11e7-81f6-97ca12eb3a28.png)
I tried to change Scan Size but still nothing shows up at all.
However if i look into the terminal output produced by the server (`npm run server`), it detects the robot.
![image](https://user-images.githubusercontent.com/22579935/28340955-3fe24006-6c1a-11e7-988b-dacd4fb08801.png)

**Comment by dunstad** [comment]
Are there any errors in the webpage's JavaScript console when you do this?

**Comment by dunstad** [comment]
For what it's worth, it seems to work better for me than you on Firefox 54.0.1: 
![firefox-54](https://user-images.githubusercontent.com/443257/28341766-f7d9c6fe-6c4f-11e7-95db-b3f13e9f7910.png)

Let's see if we can get it working for you.

**Comment by polyzium** [comment]
I guess i was too late because i wanna sleep, i will look into that tomorrow and report the results

**Comment by polyzium** [comment]
Looks like it couldn't get three.js or something.
![image](https://user-images.githubusercontent.com/22579935/28366498-ae45e5c2-6c95-11e7-982a-2b2183eb0531.png)

**Comment by dunstad** [comment]
Ah yeah I know what this is. Right now I have that library in the .gitignore since I was using the uncompressed, quite large version. I'll get that into the main repository in a few hours here and then you should be able to get things working if you clone the latest commit after that. I'll post here again when I've done it.

**Comment by polyzium** [comment]
Somehow got it working.
![image](https://user-images.githubusercontent.com/22579935/28367690-908942a4-6c9a-11e7-89c3-c8525e1e1287.png)

**Comment by dunstad** [comment]
Glad to hear it! I'll close this once I've got three.js properly in the repository then.

**Comment by dunstad** [comment]
Okay, three.min.js is properly in the repository now. I'll probably add this fix along with a few others to a 1.0.1 release in the near future. Until then, anyone who runs into this can either use the latest commit or edit the three.js import on their own. It shouldn't affect anyone using the desktop versions.
