### ISSUE TITLE
robot can't connect to server

### ISSUE THREAD

**Issue by MR-Spagetty** [dunstad/roboserver#25]
I have been unable to get this to control a robot on a dedicated server every time I setup the robot it just gives the `address could not be parsed or no valid port given` error

**Comment by MR-Spagetty** [comment]
just realised i neglected to mention i am using the desktop version of the server

**Comment by MR-Spagetty** [comment]
also i am on minecraft 1.12.2 and OC 1.7.5.192

**Comment by MR-Spagetty** [comment]
also does not seem to want to work in single player

**Comment by EzequielDM** [comment]
Same here, would love to try this out but I just couldn't understand why this is happening

**Comment by Pokruk** [comment]
Apparently I spent an hour of my life trying to launch a non-working piece of software

**Comment by dunstad** [comment]
Let this thread be a warning for anyone else who finds this: I haven't touched this in ages and I can't help you debug it, so expect problems and expect to handle them yourself. Best wishes.
