### ISSUE TITLE
Desktop app is 7 dollars!

### ISSUE THREAD

**Issue by system86** [dunstad/roboserver#5]
Holy hell that is expensive, fix pl0x

**Comment by dunstad** [comment]
Thanks for your interest! Please keep issues on this repository focused on bugs and code quality.

**Comment by dunstad** [comment]
If you want to discuss this or other topics, you can reach me on [Twitter ](https://twitter.com/Dunstad)and [Reddit](https://www.reddit.com/user/dunstad1/).

**Comment by system86** [comment]
i use neither lol
